PowersmashIOS\ReservationBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: PowersmashIOS\ReservationBundle\Entity\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        memId:
            type: integer
            column: mem_id
        date:
            type: date
        time:
            type: time
        courtId:
            type: integer
            column: court_id
    lifecycleCallbacks: {  }
