powersmash_ios_play:
    resource: "@PowersmashIOSPlayBundle/Resources/config/routing.yml"
    prefix:   /play

powersmash_ios_reservation:
    resource: "@PowersmashIOSReservationBundle/Resources/config/routing.yml"
    prefix:   /members

powersmash_ios_blog:
    resource: "@PowersmashIOSBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

powersmash_ios_admin:
    resource: "@PowersmashIOSAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
