blog_homepage:
    path:     /{page}
    defaults: { _controller: PowersmashIOSBlogBundle:Blog:index, page: 1 }
    requirements:
      page: \d+

#blog_slug:
#    path:     /{slug}
#    defaults: { _controller: PowersmashIOSBlogBundle:Blog:slug,  }
