main_homepage:
    path:     /
    defaults: { _controller: PowersmashIOSMainBundle:Main:index }
main_about:
    path:     /about
    defaults: { _controller: PowersmashIOSMainBundle:Main:about }
main_contact:
    path:     /contact
    defaults: { _controller: PowersmashIOSMainBundle:Main:contact }
